"""Copy one Hermes session's structured private record beside its task.

Hermes owns its live session database.  Foxhound deliberately does not parse
the terminal transcript to reconstruct an execution: it tags the one-shot
session with a unique source and copies the corresponding structured rows only
after the runtime has stopped.  The copied JSON is private task evidence; it
is not a result artifact and is never offered to a repository or forge.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
import sqlite3
from typing import Any, Iterable
from urllib.parse import quote


RUNTIME_SESSION_LOG_NAME = "runtime-session.json"
DEFAULT_RUNTIME_LOG_RETENTION_BYTES = 30 * 1024 * 1024


class RuntimeSessionLogError(RuntimeError):
    """The configured runtime session record could not be copied safely."""


def write_runtime_session_log(
    database: Path,
    *,
    source: str,
    destination: Path,
    turn_budget: int,
) -> Path:
    """Write the complete structured runtime record for exactly one source.

    The source is generated by Foxhound for a single run, so this lookup does
    not rely on a rendered line, timestamp window, or host-global session ID.
    """
    if (
        not isinstance(database, Path)
        or not database.is_absolute()
        or not isinstance(source, str)
        or not source
        or not isinstance(destination, Path)
        or isinstance(turn_budget, bool)
        or not isinstance(turn_budget, int)
        or turn_budget < 1
    ):
        raise RuntimeSessionLogError("runtime session log configuration is invalid")
    try:
        uri = "file:" + quote(str(database)) + "?mode=ro"
        connection = sqlite3.connect(uri, uri=True)
    except sqlite3.Error as exc:
        raise RuntimeSessionLogError("runtime session record is unavailable") from exc
    try:
        sessions = _rows(connection, "sessions", "source = ?", (source,))
        if len(sessions) != 1:
            raise RuntimeSessionLogError("runtime session record is unavailable")
        session = sessions[0]
        session_id = session.get("id")
        if not isinstance(session_id, str) or not session_id:
            raise RuntimeSessionLogError("runtime session record is invalid")
        lineage = _session_lineage(connection, session_id)
        message_rows = _messages(connection, lineage)
    finally:
        connection.close()
    document = {
        "schema": "foxhound.runtime-session-log",
        "schema_version": 1,
        "source": source,
        "run": {"turn_budget": turn_budget},
        "sessions": lineage,
        "messages": message_rows,
    }
    _write_private_json(destination / RUNTIME_SESSION_LOG_NAME, document)
    return destination / RUNTIME_SESSION_LOG_NAME


def rotate_runtime_session_logs(
    task_directory: Path,
    *,
    retain_bytes: int,
    current_directory: Path,
) -> tuple[Path, ...]:
    """Keep the newest complete logs within the deployment-owned byte budget.

    Never remove the active run's record.  A single record can exceed the
    budget; retaining it is preferable to silently turning the current run
    into the only unexplainable one.
    """
    if (
        not isinstance(retain_bytes, int)
        or isinstance(retain_bytes, bool)
        or retain_bytes < 1
    ):
        raise RuntimeSessionLogError("runtime session log retention is invalid")
    runs = task_directory / "runs"
    try:
        candidates = [
            path for path in runs.glob("*/" + RUNTIME_SESSION_LOG_NAME)
            if path.is_file() and not path.is_symlink()
        ]
        candidates.sort(key=lambda path: (path.stat().st_mtime_ns, path.parent.name))
        total = sum(path.stat().st_size for path in candidates)
    except OSError as exc:
        raise RuntimeSessionLogError("runtime session log retention is unavailable") from exc
    removed: list[Path] = []
    for path in candidates:
        if total <= retain_bytes:
            break
        if path.parent == current_directory:
            continue
        try:
            size = path.stat().st_size
            path.unlink()
        except OSError as exc:
            raise RuntimeSessionLogError("runtime session log retention is unavailable") from exc
        total -= size
        removed.append(path)
    return tuple(removed)


def _session_lineage(connection: sqlite3.Connection, session_id: str) -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = []
    pending = [session_id]
    seen: set[str] = set()
    while pending:
        current = pending.pop(0)
        if current in seen:
            continue
        seen.add(current)
        rows = _rows(connection, "sessions", "id = ?", (current,))
        if len(rows) != 1:
            raise RuntimeSessionLogError("runtime session record is invalid")
        row = rows[0]
        result.append(row)
        if _has_column(connection, "sessions", "parent_session_id"):
            children = _rows(connection, "sessions", "parent_session_id = ?", (current,))
            for child in children:
                child_id = child.get("id")
                if isinstance(child_id, str) and child_id:
                    pending.append(child_id)
    return result


def _messages(connection: sqlite3.Connection, sessions: Iterable[dict[str, Any]]) -> list[dict[str, Any]]:
    ids = [row.get("id") for row in sessions]
    if not ids or not all(isinstance(item, str) and item for item in ids):
        raise RuntimeSessionLogError("runtime session record is invalid")
    placeholders = ",".join("?" for _ in ids)
    return _rows(connection, "messages", "session_id IN (" + placeholders + ")", tuple(ids), order="session_id, id")


def _has_column(connection: sqlite3.Connection, table: str, column: str) -> bool:
    try:
        return column in {str(row[1]) for row in connection.execute("PRAGMA table_info(" + table + ")")}
    except sqlite3.Error as exc:
        raise RuntimeSessionLogError("runtime session record is unavailable") from exc


def _rows(
    connection: sqlite3.Connection,
    table: str,
    where: str,
    values: tuple[object, ...],
    *,
    order: str = "id",
) -> list[dict[str, Any]]:
    try:
        cursor = connection.execute(
            "SELECT * FROM " + table + " WHERE " + where + " ORDER BY " + order,
            values,
        )
        columns = [str(item[0]) for item in cursor.description or ()]
        return [dict(zip(columns, (_json_value(value) for value in row))) for row in cursor]
    except sqlite3.Error as exc:
        raise RuntimeSessionLogError("runtime session record is unavailable") from exc


def _json_value(value: object) -> Any:
    if value is None or isinstance(value, (str, int, float)):
        return value
    raise RuntimeSessionLogError("runtime session record is invalid")


def _write_private_json(path: Path, document: dict[str, Any]) -> None:
    encoded = (json.dumps(document, ensure_ascii=False, sort_keys=True) + "\n").encode("utf-8")
    try:
        descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC | os.O_NOFOLLOW, 0o600)
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(encoded)
    except OSError as exc:
        raise RuntimeSessionLogError("runtime session log is unavailable") from exc
