"""Versioned external contracts accepted by Foxhound."""

from .task_candidate import (
    CandidateEvidence,
    CandidateSource,
    CandidateTask,
    ContractError,
    TaskCandidate,
    candidate_id_for,
    parse_task_candidate,
    task_candidate_document,
)
from .candidate_feed import (
    CandidateFeed,
    CandidateFeedItem,
    FeedContractError,
    parse_candidate_feed,
)
from .task_shadow_observation import (
    LegacyTaskObservation,
    ShadowObservationError,
    TaskShadowObservation,
    candidate_comparable_digest,
    comparable_task_digest,
    parse_task_shadow_observation,
    parse_task_shadow_observation_json,
    task_shadow_observation_document,
)
from .task_shadow_feed import (
    ShadowFeedContractError,
    TaskShadowFeed,
    TaskShadowFeedItem,
    parse_task_shadow_feed,
    task_shadow_feed_document,
)
from .task_owner_equivalence import (
    EQUIVALENCE_BASIS,
    OwnerEquivalenceContractError,
    OwnerEquivalenceResolutionError,
    OwnerEquivalenceRequest,
    TaskOwnerEquivalence,
    owner_equivalence_request,
    owner_equivalence_request_document,
    parse_owner_equivalence_response,
    task_owner_equivalence_document,
)
from .task_lifecycle_outcome import (
    LegacyTaskCorrelation,
    LifecycleOutcomeContractError,
    TaskLifecycleOutcome,
    parse_task_lifecycle_outcome,
    task_lifecycle_outcome_document,
)
from .task_lifecycle_outcome_feed import (
    LifecycleOutcomeFeedContractError,
    TaskLifecycleOutcomeFeed,
    TaskLifecycleOutcomeFeedItem,
    parse_task_lifecycle_outcome_feed,
    task_lifecycle_outcome_feed_document,
)

__all__ = (
    "CandidateEvidence",
    "CandidateFeed",
    "CandidateFeedItem",
    "CandidateSource",
    "CandidateTask",
    "ContractError",
    "FeedContractError",
    "EQUIVALENCE_BASIS",
    "LegacyTaskObservation",
    "LegacyTaskCorrelation",
    "LifecycleOutcomeContractError",
    "LifecycleOutcomeFeedContractError",
    "OwnerEquivalenceContractError",
    "OwnerEquivalenceResolutionError",
    "OwnerEquivalenceRequest",
    "ShadowObservationError",
    "ShadowFeedContractError",
    "TaskCandidate",
    "TaskLifecycleOutcome",
    "TaskLifecycleOutcomeFeed",
    "TaskLifecycleOutcomeFeedItem",
    "TaskOwnerEquivalence",
    "TaskShadowObservation",
    "TaskShadowFeed",
    "TaskShadowFeedItem",
    "candidate_id_for",
    "candidate_comparable_digest",
    "comparable_task_digest",
    "parse_task_candidate",
    "parse_task_lifecycle_outcome",
    "parse_task_lifecycle_outcome_feed",
    "parse_candidate_feed",
    "owner_equivalence_request",
    "owner_equivalence_request_document",
    "parse_owner_equivalence_response",
    "parse_task_shadow_observation",
    "parse_task_shadow_observation_json",
    "parse_task_shadow_feed",
    "task_candidate_document",
    "task_lifecycle_outcome_document",
    "task_lifecycle_outcome_feed_document",
    "task_owner_equivalence_document",
    "task_shadow_observation_document",
    "task_shadow_feed_document",
)
